package org.skywind.one;

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
 * <p>
 * 2^2=4, 2^3=8, 2^4=16, 2^5=32
 * 3^2=9, 3^3=27, 3^4=81, 3^5=243
 * 4^2=16, 4^3=64, 4^4=256, 4^5=1024
 * 5^2=25, 5^3=125, 5^4=625, 5^5=3125
 * <p>
 * If they are then placed in numerical order, with any repeats removed,
 * we get the following sequence of 15 distinct terms:
 * <p>
 * 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
 * <p>
 * How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
 * <p>
 * Author: Sergey Saiyan sergey.sova42@gmail.com
 * Created at 21/05/2017.
 */
public class P029 {

    public static void main(String[] args) {
        System.out.println(naiveSolution(100));
    }

    private static int naiveSolution(int n) {
        Set<BigInteger> set = new HashSet<>();
        for (int a = 2; a <= n; a++) {
            BigInteger ba = new BigInteger(String.valueOf(a));
            for (int b = 2; b <= n; b++) {
                set.add(ba.pow(b));
            }
        }
        return set.size();
    }
}
