package org.skywind.one;

import org.skywind.util.Numbers;
import org.skywind.util.Search;

/**
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 * <p>
 * Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, 21, 28, 36, 45, 55, 66
 * Pentagonal	Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
 * Hexagonal	Hn=n(2n−1)	 	1, 6, 15, 28, 45, 66, 91
 * It can be verified that T285 = P165 = H143 = 40755.
 * <p>
 * Find the next triangle number that is also pentagonal and hexagonal.
 * <p>
 * Author: Sergey Saiyan sergey.sova42@gmail.com
 * Created at 27/05/2017.
 */
public class P045 {

    public static void main(String[] args) {
        int size = 1_000_000;
        long[] triangles = Numbers.triangles(size);
        long[] pentagonals = Numbers.pentagonals(size);
        long[] hexagonals = Numbers.hexagonals(size);

        for (int t = 0; t < size; t++) {
            long triangle = triangles[t];

            long pentagonal;
            for (int p = Search.binary(pentagonals, triangle);
                 p < size && (pentagonal = pentagonals[p]) <= triangle;
                 p++) {

                if (pentagonal != triangle) continue;

                long hexagonal;
                for (int h = Search.binary(hexagonals, triangle);
                     h < size && (hexagonal = hexagonals[h]) <= pentagonal;
                     h++) {
                    if (triangle == hexagonal) {
                        System.out.println((t + 1) + " " + (p + 1) + " " + (h + 1) + " " + triangle);
                    }
                }
            }
        }
    }
}
